// flow-typed signature: f54feb787cb8eb6e5c02172a3779f02d
// flow-typed version: <<STUB>>/js-sha256_v^0.9.0/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-sha256'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-sha256' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-sha256/build/sha256.min' {
  declare module.exports: any;
}

declare module 'js-sha256/src/sha256' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-sha256/build/sha256.min.js' {
  declare module.exports: $Exports<'js-sha256/build/sha256.min'>;
}
declare module 'js-sha256/src/sha256.js' {
  declare module.exports: $Exports<'js-sha256/src/sha256'>;
}
