#!/bin/bash

BUCKET=abstract-sdk-website

# Install the AWS CLI
sudo apt-get update
sudo apt-get install -y awscli

# Generate static HTML
cd website
yarn install --frozen-lockfile
yarn run build

# Upload assets then HTML
aws s3 cp ./build/abstract-sdk/ s3://$BUCKET/ --recursive --include "*" --acl public-read

# Purge Fastly cache
curl -X POST --header "Fastly-Key: $FASTLY_TOKEN" https://api.fastly.com/service/6ArsCpVh1jHIbscuig0Ric/purge_all
