// flow-typed signature: 06a5c5e8be7f7076e60ddfa011f377cf
// flow-typed version: <<STUB>>/@elasticprojects/abstract-cli_v^2.3.0/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@elasticprojects/abstract-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@elasticprojects/abstract-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@elasticprojects/abstract-cli/index' {
  declare module.exports: $Exports<'@elasticprojects/abstract-cli'>;
}
declare module '@elasticprojects/abstract-cli/index.js' {
  declare module.exports: $Exports<'@elasticprojects/abstract-cli'>;
}
