// flow-typed signature: 85eedc35439cfd226fb8200e778aab23
// flow-typed version: <<STUB>>/@elasticprojects/eslint-config-abstract_v^4.1.0/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@elasticprojects/eslint-config-abstract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@elasticprojects/eslint-config-abstract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@elasticprojects/eslint-config-abstract/index' {
  declare module.exports: $Exports<'@elasticprojects/eslint-config-abstract'>;
}
declare module '@elasticprojects/eslint-config-abstract/index.js' {
  declare module.exports: $Exports<'@elasticprojects/eslint-config-abstract'>;
}
