name: Core checks

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"
  push:
    paths-ignore:
      - "docs/**"
      - "website/**"

jobs:
  Checks:
    uses: ./.github/workflows/shared_checks.yml
    secrets: inherit
