name: Lint and Test

on:
  workflow_call:

jobs:
  SkipConcurrentBuild:
    name: Skip Concurrent Builds

    runs-on: ubuntu-latest

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - uses: fkirc/skip-duplicate-actions@v5.3.0
        id: skip_check
        with:
          concurrent_skipping: "same_content"
          github_token: ${{ github.token }}
          do_not_skip: '["pull_request"]'
          cancel_others: "true"
          skip_after_successful_duplicate: "false"

  LintAndTest:
    needs:
      - SkipConcurrentBuild

    if: ${{ needs.SkipConcurrentBuild.outputs.should_skip != 'true' }}

    name: Lint and Test

    runs-on: ubuntu-latest

    env:
      DEBUG: "abstract:*"
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - uses: actions/cache@v3
        with:
          path: flow-typed
          key: ${{ runner.os }}-flow-typed-v1-${{ hashFiles('yarn.lock', '.nvmrc') }}

      - run: yarn

      - run: yarn lint && yarn check-ts-types

      - run: yarn flow

      - run: yarn test
