name: Build Web Site

on:
  pull_request:
    branches:
      - master
    paths:
      - "website/**"
      - "docs/**"
  push:
    paths:
      - "website/**"
      - "docs/**"

jobs:
  Website:
    uses: ./.github/workflows/shared_website.yml
    secrets: inherit
